development:
  adapter: postgresql
  database: api_server_development
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: api_server_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: api_server_production
  pool: 5
  timeout: 5000