const ActionTypes = {
  CHANGE_FILTER: 'CHANGE_FILTER',
  SWITCH_MAIN: 'SWITCH_MAIN',
  SELECT_AIRCRAFT: 'SELECT_AIRCRAFT',
  SCHEDULE_TEST_FLIGHT: 'SCHEDULE_TEST_FLIGHT',
  CANCEL_TEST_FLIGHT: 'CANCEL_TEST_FLIGHT',
  CHANGE_FORM_VISIBILITY: 'CHANGE_FORM_VISIBILITY',
  LOGIN_USER: 'LOGIN_USER',
  LOGOUT_USER: 'LOGOUT_USER',
};

export default ActionTypes;
