const ActionTypes = {
  CHANGE_FILTER: 'CHANGE_FILTER',
  SELECT_AIRCRAFT: 'SELECT_AIRCRAFT',
  SCHEDULE_TEST_FLIGHT: 'SCHEDULE_TEST_FLIGHT',
  CANCEL_TEST_FLIGHT: 'CANCEL_TEST_FLIGHT',
  CHANGE_FORM_VISIBILITY: 'CHANGE_FORM_VISIBILITY',
  LOGIN_USER: 'LOGIN_USER',
  LOGOUT_USER: 'LOGOUT_USER',
  FETCH_AIRCRAFTS_BEGIN: 'FETCH_AIRCRAFTS_BEGIN',
  FETCH_AIRCRAFTS_SUCCESS: 'FETCH_AIRCRAFTS_SUCCESS',
  FETCH_AIRCRAFTS_FAILURE: 'FETCH_AIRCRAFTS_FAILURE',
  FETCH_USERS_BEGIN: 'FETCH_USERS_BEGIN',
  FETCH_USERS_SUCCESS: 'FETCH_USERS_SUCCESS',
  FETCH_USERS_FAILURE: 'FETCH_USERS_FAILURE',
  FETCH_TESTFLIGHTS_BEGIN: 'FETCH_TESTFLIGHTS_BEGIN',
  FETCH_TESTFLIGHTS_SUCCESS: 'FETCH_TESTFLIGHTS_SUCCESS',
  FETCH_TESTFLIGHTS_FAILURE: 'FETCH_TESTFLIGHTS_FAILURE',
};

export default ActionTypes;
