const ActionTypes = {
  CHANGE_FILTER: 'CHANGE_FILTER',
  SWITCH_MAIN: 'SWITCH_MAIN',
  SELECT_AIRCRAFT: 'SELECT_AIRCRAFT',
  SCHEDULE_TEST_FLIGHT: 'SCHEDULE_TEST_FLIGHT',
  CANCEL_TEST_FLIGHT: 'CANCEL_TEST_FLIGHT',
  GET_AIRCRAFTS: 'GET_AIRCRAFTS',
};

export default ActionTypes;
